### ISSUE TITLE
Crash on other user's profile

### ISSUE THREAD

**Issue by EvansPie** [EvansPie/friskal#2]
If you press like or save from the quick view, the app crashes.

![Simulator Screen Shot - iPhone 8 - 2019-09-17 at 10.38.38.png](https://images.zenhubusercontent.com/599beea28f62dc7798c39d1b/75f1b6e9-5c3d-4458-8a5d-6e3afb48335f)

**Comment by NikosVrakas** [comment]
Vangeli nomizw oti einai fixed auto e?
