### ISSUE TITLE
Search: Different font sizes in iOS search result list

### ISSUE THREAD

**Issue by NikosVrakas** [EvansPie/friskal#6]
When you search with a keyword like "coffee" that has a lot of results, the result list comes with different font sizes for some entries.

It is not visible in Android.

**Comment by NikosVrakas** [comment]
![result_list_font_ios.PNG](https://images.zenhubusercontent.com/5d7fc1afc6d30e0001febb75/3df185c5-4186-4520-87f5-f7f8c79c2379)

**Comment by EvansPie** [comment]
The problem is that the custom font provided by Nikos (`Dosis`) doesn't support Greek, so it falls back on the system font. The same will happen with other languages except if you want to use a font that supports all languages.

**Comment by NikosVrakas** [comment]
In android however we don’t see such a behavior, all the fonts are the same in the results list.

Aren’t we using the same fonts there?

**Comment by EvansPie** [comment]
The system font is probably similar, that's why you cannot observe it.

**Comment by hmakridis** [comment]
Maybe we should consider removing this feature of showing the experience titles on search. They aren't usable so I cannot see any value like this. 
Maybe it is more useful to just show "We found 5 experiences" instead
