### ISSUE TITLE
Search Box & Experience Create Tile Textbox: Tall letters are trimmed in search box

### ISSUE THREAD

**Issue by NikosVrakas** [EvansPie/friskal#7]
In Android the top of the tall and capital letters are trimmed. It's looks like there is a white padding on top of the search box that causes the issue.

**Comment by NikosVrakas** [comment]
![adnroid_search_trimmed.png](https://images.zenhubusercontent.com/5d7fc1afc6d30e0001febb75/97fbf1cd-19d4-479d-b7fb-a3223a12e3dd)

**Comment by hmakridis** [comment]
Should also put max characters when I type many it gets outside of the box. We don't need to search for something this big

**Comment by NikosVrakas** [comment]
In the latest build the problem is even worst. Almost the half of the letters is not visible!
